//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.SystemService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemService.ISystem")]
    public interface ISystem {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/AddSystemCountryCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/AddSystemCountryCodeResponse")]
        System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/GetSingleSystemCountryCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemCountryCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/UpdateSystemCountryCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemCountryCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/RemoveSystemCountryCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemCountryCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemCountryCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/AddSystemLanguageCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/AddSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/AddSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetAllSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetAllSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/GetSingleSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/GetSingleSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/UpdateSystemLanguageCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/UpdateSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/UpdateSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SystemService.ValidationFault), Action="http://tempuri.org/ISystem/RemoveSystemLanguageCodeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystem/RemoveSystemLanguageCode", ReplyAction="http://tempuri.org/ISystem/RemoveSystemLanguageCodeResponse")]
        System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemChannel : CareerCloud.UnitTests.Assignment5.SystemService.ISystem, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.SystemService.ISystem>, CareerCloud.UnitTests.Assignment5.SystemService.ISystem {
        
        public SystemClient() {
        }
        
        public SystemClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            base.Channel.AddSystemCountryCode(list);
        }
        
        public System.Threading.Tasks.Task AddSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            return base.Channel.AddSystemCountryCodeAsync(list);
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco[] GetAllSystemCountryCode() {
            return base.Channel.GetAllSystemCountryCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco[]> GetAllSystemCountryCodeAsync() {
            return base.Channel.GetAllSystemCountryCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemCountryCodePoco GetSingleSystemCountryCode(string Id) {
            return base.Channel.GetSingleSystemCountryCode(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemCountryCodePoco> GetSingleSystemCountryCodeAsync(string Id) {
            return base.Channel.GetSingleSystemCountryCodeAsync(Id);
        }
        
        public void UpdateSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            base.Channel.UpdateSystemCountryCode(list);
        }
        
        public System.Threading.Tasks.Task UpdateSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            return base.Channel.UpdateSystemCountryCodeAsync(list);
        }
        
        public void RemoveSystemCountryCode(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            base.Channel.RemoveSystemCountryCode(list);
        }
        
        public System.Threading.Tasks.Task RemoveSystemCountryCodeAsync(CareerCloud.Pocos.SystemCountryCodePoco[] list) {
            return base.Channel.RemoveSystemCountryCodeAsync(list);
        }
        
        public void AddSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            base.Channel.AddSystemLanguageCode(list);
        }
        
        public System.Threading.Tasks.Task AddSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            return base.Channel.AddSystemLanguageCodeAsync(list);
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco[] GetAllSystemLanguageCode() {
            return base.Channel.GetAllSystemLanguageCode();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco[]> GetAllSystemLanguageCodeAsync() {
            return base.Channel.GetAllSystemLanguageCodeAsync();
        }
        
        public CareerCloud.Pocos.SystemLanguageCodePoco GetSingleSystemLanguageCode(string Id) {
            return base.Channel.GetSingleSystemLanguageCode(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SystemLanguageCodePoco> GetSingleSystemLanguageCodeAsync(string Id) {
            return base.Channel.GetSingleSystemLanguageCodeAsync(Id);
        }
        
        public void UpdateSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            base.Channel.UpdateSystemLanguageCode(list);
        }
        
        public System.Threading.Tasks.Task UpdateSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            return base.Channel.UpdateSystemLanguageCodeAsync(list);
        }
        
        public void RemoveSystemLanguageCode(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            base.Channel.RemoveSystemLanguageCode(list);
        }
        
        public System.Threading.Tasks.Task RemoveSystemLanguageCodeAsync(CareerCloud.Pocos.SystemLanguageCodePoco[] list) {
            return base.Channel.RemoveSystemLanguageCodeAsync(list);
        }
    }
}
