//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.ApplicantService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ApplicantService.IApplicant")]
    public interface IApplicant {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/AddApplicantEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/AddApplicantEducationResponse")]
        System.Threading.Tasks.Task AddApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantEducationResponse")]
        CareerCloud.Pocos.ApplicantEducationPoco[] GetAllApplicantEducation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco[]> GetAllApplicantEducationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantEducationPoco GetSingleApplicantEducation(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco> GetSingleApplicantEducationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantEducationResponse")]
        System.Threading.Tasks.Task UpdateApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantEducation", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantEducationResponse")]
        System.Threading.Tasks.Task RemoveApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/AddApplicantJobApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantJobApplicationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/AddApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task AddApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantJobApplicationResponse")]
        CareerCloud.Pocos.ApplicantJobApplicationPoco[] GetAllApplicantJobApplication();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco[]> GetAllApplicantJobApplicationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantJobApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantJobApplicationValidationFaultFaul" +
            "t", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantJobApplicationPoco GetSingleApplicantJobApplication(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco> GetSingleApplicantJobApplicationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantJobApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantJobApplicationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task UpdateApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantJobApplicationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantJobApplicationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantJobApplication", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantJobApplicationResponse")]
        System.Threading.Tasks.Task RemoveApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/AddApplicantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/AddApplicantProfileResponse")]
        System.Threading.Tasks.Task AddApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantProfileResponse")]
        CareerCloud.Pocos.ApplicantProfilePoco[] GetAllApplicantProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco[]> GetAllApplicantProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantProfilePoco GetSingleApplicantProfile(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco> GetSingleApplicantProfileAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantProfileResponse")]
        System.Threading.Tasks.Task UpdateApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantProfile", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantProfileResponse")]
        System.Threading.Tasks.Task RemoveApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantResume", ReplyAction="http://tempuri.org/IApplicant/AddApplicantResumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantResumeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantResume", ReplyAction="http://tempuri.org/IApplicant/AddApplicantResumeResponse")]
        System.Threading.Tasks.Task AddApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantResumeResponse")]
        CareerCloud.Pocos.ApplicantResumePoco[] GetAllApplicantResume();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantResumeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco[]> GetAllApplicantResumeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantResumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantResumeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantResumePoco GetSingleApplicantResume(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantResume", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantResumeResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco> GetSingleApplicantResumeAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantResume", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantResumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantResumeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantResume", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantResumeResponse")]
        System.Threading.Tasks.Task UpdateApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantResume", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantResumeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantResumeValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantResume", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantResumeResponse")]
        System.Threading.Tasks.Task RemoveApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/AddApplicantSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/AddApplicantSkillResponse")]
        System.Threading.Tasks.Task AddApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantSkillResponse")]
        CareerCloud.Pocos.ApplicantSkillPoco[] GetAllApplicantSkill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco[]> GetAllApplicantSkillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantSkillPoco GetSingleApplicantSkill(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco> GetSingleApplicantSkillAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantSkillResponse")]
        System.Threading.Tasks.Task UpdateApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantSkill", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantSkillResponse")]
        System.Threading.Tasks.Task RemoveApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/AddApplicantWorkHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/AddApplicantWorkHistoryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/AddApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/AddApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task AddApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantWorkHistoryResponse")]
        CareerCloud.Pocos.ApplicantWorkHistoryPoco[] GetAllApplicantWorkHistory();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetAllApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetAllApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco[]> GetAllApplicantWorkHistoryAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistoryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.ApplicantWorkHistoryPoco GetSingleApplicantWorkHistory(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/GetSingleApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco> GetSingleApplicantWorkHistoryAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantWorkHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/UpdateApplicantWorkHistoryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/UpdateApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/UpdateApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task UpdateApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantWorkHistoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.ApplicantService.ValidationFault), Action="http://tempuri.org/IApplicant/RemoveApplicantWorkHistoryValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IApplicant/RemoveApplicantWorkHistory", ReplyAction="http://tempuri.org/IApplicant/RemoveApplicantWorkHistoryResponse")]
        System.Threading.Tasks.Task RemoveApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IApplicantChannel : CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicantClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant>, CareerCloud.UnitTests.Assignment5.ApplicantService.IApplicant {
        
        public ApplicantClient() {
        }
        
        public ApplicantClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicantClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicantClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicantClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            base.Channel.AddApplicantEducation(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            return base.Channel.AddApplicantEducationAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantEducationPoco[] GetAllApplicantEducation() {
            return base.Channel.GetAllApplicantEducation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco[]> GetAllApplicantEducationAsync() {
            return base.Channel.GetAllApplicantEducationAsync();
        }
        
        public CareerCloud.Pocos.ApplicantEducationPoco GetSingleApplicantEducation(string Id) {
            return base.Channel.GetSingleApplicantEducation(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantEducationPoco> GetSingleApplicantEducationAsync(string Id) {
            return base.Channel.GetSingleApplicantEducationAsync(Id);
        }
        
        public void UpdateApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            base.Channel.UpdateApplicantEducation(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            return base.Channel.UpdateApplicantEducationAsync(list);
        }
        
        public void RemoveApplicantEducation(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            base.Channel.RemoveApplicantEducation(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantEducationAsync(CareerCloud.Pocos.ApplicantEducationPoco[] list) {
            return base.Channel.RemoveApplicantEducationAsync(list);
        }
        
        public void AddApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            base.Channel.AddApplicantJobApplication(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            return base.Channel.AddApplicantJobApplicationAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantJobApplicationPoco[] GetAllApplicantJobApplication() {
            return base.Channel.GetAllApplicantJobApplication();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco[]> GetAllApplicantJobApplicationAsync() {
            return base.Channel.GetAllApplicantJobApplicationAsync();
        }
        
        public CareerCloud.Pocos.ApplicantJobApplicationPoco GetSingleApplicantJobApplication(string Id) {
            return base.Channel.GetSingleApplicantJobApplication(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantJobApplicationPoco> GetSingleApplicantJobApplicationAsync(string Id) {
            return base.Channel.GetSingleApplicantJobApplicationAsync(Id);
        }
        
        public void UpdateApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            base.Channel.UpdateApplicantJobApplication(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            return base.Channel.UpdateApplicantJobApplicationAsync(list);
        }
        
        public void RemoveApplicantJobApplication(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            base.Channel.RemoveApplicantJobApplication(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantJobApplicationAsync(CareerCloud.Pocos.ApplicantJobApplicationPoco[] list) {
            return base.Channel.RemoveApplicantJobApplicationAsync(list);
        }
        
        public void AddApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            base.Channel.AddApplicantProfile(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            return base.Channel.AddApplicantProfileAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantProfilePoco[] GetAllApplicantProfile() {
            return base.Channel.GetAllApplicantProfile();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco[]> GetAllApplicantProfileAsync() {
            return base.Channel.GetAllApplicantProfileAsync();
        }
        
        public CareerCloud.Pocos.ApplicantProfilePoco GetSingleApplicantProfile(string Id) {
            return base.Channel.GetSingleApplicantProfile(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantProfilePoco> GetSingleApplicantProfileAsync(string Id) {
            return base.Channel.GetSingleApplicantProfileAsync(Id);
        }
        
        public void UpdateApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            base.Channel.UpdateApplicantProfile(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            return base.Channel.UpdateApplicantProfileAsync(list);
        }
        
        public void RemoveApplicantProfile(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            base.Channel.RemoveApplicantProfile(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantProfileAsync(CareerCloud.Pocos.ApplicantProfilePoco[] list) {
            return base.Channel.RemoveApplicantProfileAsync(list);
        }
        
        public void AddApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            base.Channel.AddApplicantResume(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            return base.Channel.AddApplicantResumeAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantResumePoco[] GetAllApplicantResume() {
            return base.Channel.GetAllApplicantResume();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco[]> GetAllApplicantResumeAsync() {
            return base.Channel.GetAllApplicantResumeAsync();
        }
        
        public CareerCloud.Pocos.ApplicantResumePoco GetSingleApplicantResume(string Id) {
            return base.Channel.GetSingleApplicantResume(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantResumePoco> GetSingleApplicantResumeAsync(string Id) {
            return base.Channel.GetSingleApplicantResumeAsync(Id);
        }
        
        public void UpdateApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            base.Channel.UpdateApplicantResume(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            return base.Channel.UpdateApplicantResumeAsync(list);
        }
        
        public void RemoveApplicantResume(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            base.Channel.RemoveApplicantResume(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantResumeAsync(CareerCloud.Pocos.ApplicantResumePoco[] list) {
            return base.Channel.RemoveApplicantResumeAsync(list);
        }
        
        public void AddApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            base.Channel.AddApplicantSkill(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            return base.Channel.AddApplicantSkillAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantSkillPoco[] GetAllApplicantSkill() {
            return base.Channel.GetAllApplicantSkill();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco[]> GetAllApplicantSkillAsync() {
            return base.Channel.GetAllApplicantSkillAsync();
        }
        
        public CareerCloud.Pocos.ApplicantSkillPoco GetSingleApplicantSkill(string Id) {
            return base.Channel.GetSingleApplicantSkill(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantSkillPoco> GetSingleApplicantSkillAsync(string Id) {
            return base.Channel.GetSingleApplicantSkillAsync(Id);
        }
        
        public void UpdateApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            base.Channel.UpdateApplicantSkill(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            return base.Channel.UpdateApplicantSkillAsync(list);
        }
        
        public void RemoveApplicantSkill(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            base.Channel.RemoveApplicantSkill(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantSkillAsync(CareerCloud.Pocos.ApplicantSkillPoco[] list) {
            return base.Channel.RemoveApplicantSkillAsync(list);
        }
        
        public void AddApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            base.Channel.AddApplicantWorkHistory(list);
        }
        
        public System.Threading.Tasks.Task AddApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            return base.Channel.AddApplicantWorkHistoryAsync(list);
        }
        
        public CareerCloud.Pocos.ApplicantWorkHistoryPoco[] GetAllApplicantWorkHistory() {
            return base.Channel.GetAllApplicantWorkHistory();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco[]> GetAllApplicantWorkHistoryAsync() {
            return base.Channel.GetAllApplicantWorkHistoryAsync();
        }
        
        public CareerCloud.Pocos.ApplicantWorkHistoryPoco GetSingleApplicantWorkHistory(string Id) {
            return base.Channel.GetSingleApplicantWorkHistory(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.ApplicantWorkHistoryPoco> GetSingleApplicantWorkHistoryAsync(string Id) {
            return base.Channel.GetSingleApplicantWorkHistoryAsync(Id);
        }
        
        public void UpdateApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            base.Channel.UpdateApplicantWorkHistory(list);
        }
        
        public System.Threading.Tasks.Task UpdateApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            return base.Channel.UpdateApplicantWorkHistoryAsync(list);
        }
        
        public void RemoveApplicantWorkHistory(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            base.Channel.RemoveApplicantWorkHistory(list);
        }
        
        public System.Threading.Tasks.Task RemoveApplicantWorkHistoryAsync(CareerCloud.Pocos.ApplicantWorkHistoryPoco[] list) {
            return base.Channel.RemoveApplicantWorkHistoryAsync(list);
        }
    }
}
