//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.SecurityService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityService.ISecurity")]
    public interface ISecurity {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/AddSecurityLoginValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginResponse")]
        System.Threading.Tasks.Task AddSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginResponse")]
        CareerCloud.Pocos.SecurityLoginPoco[] GetAllSecurityLogin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginPoco[]> GetAllSecurityLoginAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SecurityLoginPoco GetSingleSecurityLogin(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginPoco> GetSingleSecurityLoginAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/UpdateSecurityLoginValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginResponse")]
        System.Threading.Tasks.Task UpdateSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/RemoveSecurityLoginValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLogin", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginResponse")]
        System.Threading.Tasks.Task RemoveSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginsRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/AddSecurityLoginsRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginsRoleResponse")]
        System.Threading.Tasks.Task AddSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginsRoleResponse")]
        CareerCloud.Pocos.SecurityLoginsRolePoco[] GetAllSecurityLoginsRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginsRoleResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsRolePoco[]> GetAllSecurityLoginsRoleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginsRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SecurityLoginsRolePoco GetSingleSecurityLoginsRole(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginsRoleResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsRolePoco> GetSingleSecurityLoginsRoleAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginsRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginsRoleResponse")]
        System.Threading.Tasks.Task UpdateSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginsRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsRole", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginsRoleResponse")]
        System.Threading.Tasks.Task RemoveSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityRole", ReplyAction="http://tempuri.org/ISecurity/AddSecurityRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/AddSecurityRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityRole", ReplyAction="http://tempuri.org/ISecurity/AddSecurityRoleResponse")]
        System.Threading.Tasks.Task AddSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityRole", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityRoleResponse")]
        CareerCloud.Pocos.SecurityRolePoco[] GetAllSecurityRole();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityRole", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityRoleResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityRolePoco[]> GetAllSecurityRoleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityRole", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/GetSingleSecurityRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SecurityRolePoco GetSingleSecurityRole(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityRole", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityRoleResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityRolePoco> GetSingleSecurityRoleAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityRole", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/UpdateSecurityRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityRole", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityRoleResponse")]
        System.Threading.Tasks.Task UpdateSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityRole", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityRoleResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/RemoveSecurityRoleValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityRole", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityRoleResponse")]
        System.Threading.Tasks.Task RemoveSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginsLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/AddSecurityLoginsLogValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/AddSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/AddSecurityLoginsLogResponse")]
        System.Threading.Tasks.Task AddSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginsLogResponse")]
        CareerCloud.Pocos.SecurityLoginsLogPoco[] GetAllSecurityLoginsLog();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetAllSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/GetAllSecurityLoginsLogResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsLogPoco[]> GetAllSecurityLoginsLogAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginsLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsLogValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.SecurityLoginsLogPoco GetSingleSecurityLoginsLog(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/GetSingleSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/GetSingleSecurityLoginsLogResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsLogPoco> GetSingleSecurityLoginsLogAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginsLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsLogValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/UpdateSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/UpdateSecurityLoginsLogResponse")]
        System.Threading.Tasks.Task UpdateSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginsLogResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.SecurityService.ValidationFault), Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsLogValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurity/RemoveSecurityLoginsLog", ReplyAction="http://tempuri.org/ISecurity/RemoveSecurityLoginsLogResponse")]
        System.Threading.Tasks.Task RemoveSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityChannel : CareerCloud.UnitTests.Assignment5.SecurityService.ISecurity, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.SecurityService.ISecurity>, CareerCloud.UnitTests.Assignment5.SecurityService.ISecurity {
        
        public SecurityClient() {
        }
        
        public SecurityClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            base.Channel.AddSecurityLogin(list);
        }
        
        public System.Threading.Tasks.Task AddSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            return base.Channel.AddSecurityLoginAsync(list);
        }
        
        public CareerCloud.Pocos.SecurityLoginPoco[] GetAllSecurityLogin() {
            return base.Channel.GetAllSecurityLogin();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginPoco[]> GetAllSecurityLoginAsync() {
            return base.Channel.GetAllSecurityLoginAsync();
        }
        
        public CareerCloud.Pocos.SecurityLoginPoco GetSingleSecurityLogin(string Id) {
            return base.Channel.GetSingleSecurityLogin(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginPoco> GetSingleSecurityLoginAsync(string Id) {
            return base.Channel.GetSingleSecurityLoginAsync(Id);
        }
        
        public void UpdateSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            base.Channel.UpdateSecurityLogin(list);
        }
        
        public System.Threading.Tasks.Task UpdateSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            return base.Channel.UpdateSecurityLoginAsync(list);
        }
        
        public void RemoveSecurityLogin(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            base.Channel.RemoveSecurityLogin(list);
        }
        
        public System.Threading.Tasks.Task RemoveSecurityLoginAsync(CareerCloud.Pocos.SecurityLoginPoco[] list) {
            return base.Channel.RemoveSecurityLoginAsync(list);
        }
        
        public void AddSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            base.Channel.AddSecurityLoginsRole(list);
        }
        
        public System.Threading.Tasks.Task AddSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            return base.Channel.AddSecurityLoginsRoleAsync(list);
        }
        
        public CareerCloud.Pocos.SecurityLoginsRolePoco[] GetAllSecurityLoginsRole() {
            return base.Channel.GetAllSecurityLoginsRole();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsRolePoco[]> GetAllSecurityLoginsRoleAsync() {
            return base.Channel.GetAllSecurityLoginsRoleAsync();
        }
        
        public CareerCloud.Pocos.SecurityLoginsRolePoco GetSingleSecurityLoginsRole(string Id) {
            return base.Channel.GetSingleSecurityLoginsRole(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsRolePoco> GetSingleSecurityLoginsRoleAsync(string Id) {
            return base.Channel.GetSingleSecurityLoginsRoleAsync(Id);
        }
        
        public void UpdateSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            base.Channel.UpdateSecurityLoginsRole(list);
        }
        
        public System.Threading.Tasks.Task UpdateSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            return base.Channel.UpdateSecurityLoginsRoleAsync(list);
        }
        
        public void RemoveSecurityLoginsRole(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            base.Channel.RemoveSecurityLoginsRole(list);
        }
        
        public System.Threading.Tasks.Task RemoveSecurityLoginsRoleAsync(CareerCloud.Pocos.SecurityLoginsRolePoco[] list) {
            return base.Channel.RemoveSecurityLoginsRoleAsync(list);
        }
        
        public void AddSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list) {
            base.Channel.AddSecurityRole(list);
        }
        
        public System.Threading.Tasks.Task AddSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list) {
            return base.Channel.AddSecurityRoleAsync(list);
        }
        
        public CareerCloud.Pocos.SecurityRolePoco[] GetAllSecurityRole() {
            return base.Channel.GetAllSecurityRole();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityRolePoco[]> GetAllSecurityRoleAsync() {
            return base.Channel.GetAllSecurityRoleAsync();
        }
        
        public CareerCloud.Pocos.SecurityRolePoco GetSingleSecurityRole(string Id) {
            return base.Channel.GetSingleSecurityRole(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityRolePoco> GetSingleSecurityRoleAsync(string Id) {
            return base.Channel.GetSingleSecurityRoleAsync(Id);
        }
        
        public void UpdateSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list) {
            base.Channel.UpdateSecurityRole(list);
        }
        
        public System.Threading.Tasks.Task UpdateSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list) {
            return base.Channel.UpdateSecurityRoleAsync(list);
        }
        
        public void RemoveSecurityRole(CareerCloud.Pocos.SecurityRolePoco[] list) {
            base.Channel.RemoveSecurityRole(list);
        }
        
        public System.Threading.Tasks.Task RemoveSecurityRoleAsync(CareerCloud.Pocos.SecurityRolePoco[] list) {
            return base.Channel.RemoveSecurityRoleAsync(list);
        }
        
        public void AddSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            base.Channel.AddSecurityLoginsLog(list);
        }
        
        public System.Threading.Tasks.Task AddSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            return base.Channel.AddSecurityLoginsLogAsync(list);
        }
        
        public CareerCloud.Pocos.SecurityLoginsLogPoco[] GetAllSecurityLoginsLog() {
            return base.Channel.GetAllSecurityLoginsLog();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsLogPoco[]> GetAllSecurityLoginsLogAsync() {
            return base.Channel.GetAllSecurityLoginsLogAsync();
        }
        
        public CareerCloud.Pocos.SecurityLoginsLogPoco GetSingleSecurityLoginsLog(string Id) {
            return base.Channel.GetSingleSecurityLoginsLog(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.SecurityLoginsLogPoco> GetSingleSecurityLoginsLogAsync(string Id) {
            return base.Channel.GetSingleSecurityLoginsLogAsync(Id);
        }
        
        public void UpdateSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            base.Channel.UpdateSecurityLoginsLog(list);
        }
        
        public System.Threading.Tasks.Task UpdateSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            return base.Channel.UpdateSecurityLoginsLogAsync(list);
        }
        
        public void RemoveSecurityLoginsLog(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            base.Channel.RemoveSecurityLoginsLog(list);
        }
        
        public System.Threading.Tasks.Task RemoveSecurityLoginsLogAsync(CareerCloud.Pocos.SecurityLoginsLogPoco[] list) {
            return base.Channel.RemoveSecurityLoginsLogAsync(list);
        }
    }
}
