//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CareerCloud.UnitTests.Assignment5.CompanyService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
    [System.SerializableAttribute()]
    public partial class ValidationFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompany")]
    public interface ICompany {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyJobDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobDescription", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobDescriptionResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyJobEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobEducationResponse")]
        System.Threading.Tasks.Task AddCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobEducationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyJobEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobEducationResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyJobEducationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobEducation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobEducationResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJob", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyJobValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJob", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobResponse")]
        System.Threading.Tasks.Task AddCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyJobValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJob", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyJobValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJob", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyJobValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJob", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyJobSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/AddCompanyJobSkillResponse")]
        System.Threading.Tasks.Task AddCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyJobSkillResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyJobSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyJobSkillResponse")]
        System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyJobSkillValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyJobSkill", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyJobSkillResponse")]
        System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyLocation", ReplyAction="http://tempuri.org/ICompany/AddCompanyLocationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyLocationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyLocation", ReplyAction="http://tempuri.org/ICompany/AddCompanyLocationResponse")]
        System.Threading.Tasks.Task AddCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyLocationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyLocation", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyLocationResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyLocationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyLocation", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyLocationResponse")]
        System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyLocationValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyLocation", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyLocationResponse")]
        System.Threading.Tasks.Task RemoveCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyProfile", ReplyAction="http://tempuri.org/ICompany/AddCompanyProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/AddCompanyProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void AddCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/AddCompanyProfile", ReplyAction="http://tempuri.org/ICompany/AddCompanyProfileResponse")]
        System.Threading.Tasks.Task AddCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetAllCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetAllCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/GetSingleCompanyProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/GetSingleCompanyProfile", ReplyAction="http://tempuri.org/ICompany/GetSingleCompanyProfileResponse")]
        System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/UpdateCompanyProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/UpdateCompanyProfile", ReplyAction="http://tempuri.org/ICompany/UpdateCompanyProfileResponse")]
        System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(CareerCloud.UnitTests.Assignment5.CompanyService.ValidationFault), Action="http://tempuri.org/ICompany/RemoveCompanyProfileValidationFaultFault", Name="ValidationFault", Namespace="http://schemas.datacontract.org/2004/07/CareerCloud.WCF")]
        void RemoveCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompany/RemoveCompanyProfile", ReplyAction="http://tempuri.org/ICompany/RemoveCompanyProfileResponse")]
        System.Threading.Tasks.Task RemoveCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyChannel : CareerCloud.UnitTests.Assignment5.CompanyService.ICompany, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyClient : System.ServiceModel.ClientBase<CareerCloud.UnitTests.Assignment5.CompanyService.ICompany>, CareerCloud.UnitTests.Assignment5.CompanyService.ICompany {
        
        public CompanyClient() {
        }
        
        public CompanyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            base.Channel.AddCompanyDescription(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            return base.Channel.AddCompanyDescriptionAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco[] GetAllCompanyDescription() {
            return base.Channel.GetAllCompanyDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco[]> GetAllCompanyDescriptionAsync() {
            return base.Channel.GetAllCompanyDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyDescriptionPoco GetSingleCompanyDescription(string Id) {
            return base.Channel.GetSingleCompanyDescription(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyDescriptionPoco> GetSingleCompanyDescriptionAsync(string Id) {
            return base.Channel.GetSingleCompanyDescriptionAsync(Id);
        }
        
        public void UpdateCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            base.Channel.UpdateCompanyDescription(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            return base.Channel.UpdateCompanyDescriptionAsync(list);
        }
        
        public void RemoveCompanyDescription(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            base.Channel.RemoveCompanyDescription(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyDescriptionAsync(CareerCloud.Pocos.CompanyDescriptionPoco[] list) {
            return base.Channel.RemoveCompanyDescriptionAsync(list);
        }
        
        public void AddCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            base.Channel.AddCompanyJobDescription(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            return base.Channel.AddCompanyJobDescriptionAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco[] GetAllCompanyJobDescription() {
            return base.Channel.GetAllCompanyJobDescription();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco[]> GetAllCompanyJobDescriptionAsync() {
            return base.Channel.GetAllCompanyJobDescriptionAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobDescriptionPoco GetSingleCompanyJobDescription(string Id) {
            return base.Channel.GetSingleCompanyJobDescription(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobDescriptionPoco> GetSingleCompanyJobDescriptionAsync(string Id) {
            return base.Channel.GetSingleCompanyJobDescriptionAsync(Id);
        }
        
        public void UpdateCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            base.Channel.UpdateCompanyJobDescription(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            return base.Channel.UpdateCompanyJobDescriptionAsync(list);
        }
        
        public void RemoveCompanyJobDescription(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            base.Channel.RemoveCompanyJobDescription(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobDescriptionAsync(CareerCloud.Pocos.CompanyJobDescriptionPoco[] list) {
            return base.Channel.RemoveCompanyJobDescriptionAsync(list);
        }
        
        public void AddCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            base.Channel.AddCompanyJobEducation(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            return base.Channel.AddCompanyJobEducationAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco[] GetAllCompanyJobEducation() {
            return base.Channel.GetAllCompanyJobEducation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco[]> GetAllCompanyJobEducationAsync() {
            return base.Channel.GetAllCompanyJobEducationAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobEducationPoco GetSingleCompanyJobEducation(string Id) {
            return base.Channel.GetSingleCompanyJobEducation(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobEducationPoco> GetSingleCompanyJobEducationAsync(string Id) {
            return base.Channel.GetSingleCompanyJobEducationAsync(Id);
        }
        
        public void UpdateCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            base.Channel.UpdateCompanyJobEducation(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            return base.Channel.UpdateCompanyJobEducationAsync(list);
        }
        
        public void RemoveCompanyJobEducation(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            base.Channel.RemoveCompanyJobEducation(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobEducationAsync(CareerCloud.Pocos.CompanyJobEducationPoco[] list) {
            return base.Channel.RemoveCompanyJobEducationAsync(list);
        }
        
        public void AddCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list) {
            base.Channel.AddCompanyJob(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list) {
            return base.Channel.AddCompanyJobAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyJobPoco[] GetAllCompanyJob() {
            return base.Channel.GetAllCompanyJob();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco[]> GetAllCompanyJobAsync() {
            return base.Channel.GetAllCompanyJobAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobPoco GetSingleCompanyJob(string Id) {
            return base.Channel.GetSingleCompanyJob(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobPoco> GetSingleCompanyJobAsync(string Id) {
            return base.Channel.GetSingleCompanyJobAsync(Id);
        }
        
        public void UpdateCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list) {
            base.Channel.UpdateCompanyJob(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list) {
            return base.Channel.UpdateCompanyJobAsync(list);
        }
        
        public void RemoveCompanyJob(CareerCloud.Pocos.CompanyJobPoco[] list) {
            base.Channel.RemoveCompanyJob(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobAsync(CareerCloud.Pocos.CompanyJobPoco[] list) {
            return base.Channel.RemoveCompanyJobAsync(list);
        }
        
        public void AddCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            base.Channel.AddCompanyJobSkill(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            return base.Channel.AddCompanyJobSkillAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco[] GetAllCompanyJobSkill() {
            return base.Channel.GetAllCompanyJobSkill();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco[]> GetAllCompanyJobSkillAsync() {
            return base.Channel.GetAllCompanyJobSkillAsync();
        }
        
        public CareerCloud.Pocos.CompanyJobSkillPoco GetSingleCompanyJobSkill(string Id) {
            return base.Channel.GetSingleCompanyJobSkill(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyJobSkillPoco> GetSingleCompanyJobSkillAsync(string Id) {
            return base.Channel.GetSingleCompanyJobSkillAsync(Id);
        }
        
        public void UpdateCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            base.Channel.UpdateCompanyJobSkill(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            return base.Channel.UpdateCompanyJobSkillAsync(list);
        }
        
        public void RemoveCompanyJobSkill(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            base.Channel.RemoveCompanyJobSkill(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyJobSkillAsync(CareerCloud.Pocos.CompanyJobSkillPoco[] list) {
            return base.Channel.RemoveCompanyJobSkillAsync(list);
        }
        
        public void AddCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            base.Channel.AddCompanyLocation(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            return base.Channel.AddCompanyLocationAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco[] GetAllCompanyLocation() {
            return base.Channel.GetAllCompanyLocation();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco[]> GetAllCompanyLocationAsync() {
            return base.Channel.GetAllCompanyLocationAsync();
        }
        
        public CareerCloud.Pocos.CompanyLocationPoco GetSingleCompanyLocation(string Id) {
            return base.Channel.GetSingleCompanyLocation(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyLocationPoco> GetSingleCompanyLocationAsync(string Id) {
            return base.Channel.GetSingleCompanyLocationAsync(Id);
        }
        
        public void UpdateCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            base.Channel.UpdateCompanyLocation(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            return base.Channel.UpdateCompanyLocationAsync(list);
        }
        
        public void RemoveCompanyLocation(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            base.Channel.RemoveCompanyLocation(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyLocationAsync(CareerCloud.Pocos.CompanyLocationPoco[] list) {
            return base.Channel.RemoveCompanyLocationAsync(list);
        }
        
        public void AddCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            base.Channel.AddCompanyProfile(list);
        }
        
        public System.Threading.Tasks.Task AddCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            return base.Channel.AddCompanyProfileAsync(list);
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco[] GetAllCompanyProfile() {
            return base.Channel.GetAllCompanyProfile();
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco[]> GetAllCompanyProfileAsync() {
            return base.Channel.GetAllCompanyProfileAsync();
        }
        
        public CareerCloud.Pocos.CompanyProfilePoco GetSingleCompanyProfile(string Id) {
            return base.Channel.GetSingleCompanyProfile(Id);
        }
        
        public System.Threading.Tasks.Task<CareerCloud.Pocos.CompanyProfilePoco> GetSingleCompanyProfileAsync(string Id) {
            return base.Channel.GetSingleCompanyProfileAsync(Id);
        }
        
        public void UpdateCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            base.Channel.UpdateCompanyProfile(list);
        }
        
        public System.Threading.Tasks.Task UpdateCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            return base.Channel.UpdateCompanyProfileAsync(list);
        }
        
        public void RemoveCompanyProfile(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            base.Channel.RemoveCompanyProfile(list);
        }
        
        public System.Threading.Tasks.Task RemoveCompanyProfileAsync(CareerCloud.Pocos.CompanyProfilePoco[] list) {
            return base.Channel.RemoveCompanyProfileAsync(list);
        }
    }
}
